import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import type { Hike } from '@/types/database'

export const revalidate = 0
type Props = { params: Promise<{ slug: string }> }
type Media = { id:string; hike_id:string; image_url:string; is_main:boolean; sort_order:number }
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'-')
const valueOr=(v:string|number|null|undefined,f='To be confirmed')=>v===null||v===undefined||v===''?f:String(v)
const list=(v?:string[])=>v?.filter(Boolean)||[]

async function getData(slug:string){
 const supabase=await createClient(); const [{data:hikes},{data:media}]=await Promise.all([supabase.from('hikes').select('*').eq('status','published').order('created_at',{ascending:true}),supabase.from('hike_media').select('id,hike_id,image_url,is_main,sort_order').order('is_main',{ascending:false}).order('sort_order',{ascending:true})]); return {hike:(hikes||[]).find((h:Hike)=>slugify(h.name)===slug) as Hike|undefined,media:(media||[]) as Media[]}
}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const {hike}=await getData(slug);if(!hike)return{title:'Hike not found | Peak Axis'};return{title:`${hike.name} | Peak Axis Mauritius`,description:hike.description||`${hike.name} — guided adventure in Mauritius.`}}

export default async function HikeDetailPage({params}:Props){
 const {slug}=await params; const {hike,media}=await getData(slug); if(!hike)notFound()
 const hikeMedia=media.filter(m=>m.hike_id===hike.id),main=hikeMedia.find(m=>m.is_main)||hikeMedia[0],gallery=hikeMedia.filter(m=>m.id!==main?.id)
 const spots=hike.spots_remaining??0,isScheduled=hike.booking_type==='scheduled_group',available=!isScheduled||spots>0
 const trailStatus=hike.trail_condition_status||'open',routeUnavailable=trailStatus==='temporarily_unsuitable'||trailStatus==='closed'
 const bookingType=hike.booking_type==='private'?'private':isScheduled?'scheduled_group':'on_demand',bookingLabel=bookingType==='scheduled_group'?'Scheduled group hike':bookingType==='private'?'Private / on-demand':'On-demand hike'
 const enquiry=routeUnavailable?`/enquire?interest=private_hike&ref=${encodeURIComponent(hike.name)}`:available?`/enquire?interest=${bookingType==='scheduled_group'?'hike':'private_hike'}&ref=${encodeURIComponent(hike.name)}`:'/enquire?interest=private_hike'
 const bring=list(hike.what_to_bring),included=list(hike.included),excluded=list(hike.excluded),experience=list(hike.experience_types)
 const facts=[['Difficulty',valueOr(hike.difficulty_numeric||hike.difficulty)],['Distance',hike.distance_km!=null?`${hike.distance_km} km`:'To be confirmed'],['Duration',valueOr(hike.duration)],['Elevation gain',hike.elevation_gain_m!=null?`${hike.elevation_gain_m} m`:'To be confirmed'],['Location',valueOr(hike.location)],['Terrain',valueOr(hike.terrain)],['Fitness required',valueOr(hike.fitness_required)],['Minimum age',valueOr(hike.age_requirements)],['Group size',hike.min_participants||hike.max_participants?`${valueOr(hike.min_participants,'—')}–${valueOr(hike.max_participants,'—')}`:'To be confirmed']]
 return <div className="view active" style={{display:'block'}}><section className="pagehead" style={{padding:'60px 0 36px'}}><div className="wrap"><Link href="/hikes" style={{display:'inline-block',marginBottom:20,fontSize:14,fontWeight:600}}>← All hikes</Link><div style={{maxWidth:940}}><div style={{marginBottom:16,display:'flex',gap:14,flexWrap:'wrap',fontSize:13.5,color:'#6b675f'}}><span style={{fontWeight:700,textTransform:'capitalize'}}>{hike.difficulty}{hike.difficulty_numeric?` · ${hike.difficulty_numeric}`:''}</span><span>⏱ {hike.duration}</span><span>📍 {hike.location}</span>{hike.overall_rating!=null&&<span style={{fontWeight:700}}>★ {hike.overall_rating}/10</span>}</div><h1 style={{fontSize:'clamp(40px,6vw,64px)'}}>{hike.name}</h1><p style={{marginTop:18,maxWidth:780,fontSize:17,lineHeight:1.7,color:'#3d3a36'}}>{hike.description||`Join Peak Axis for ${hike.name}, a guided hike in Mauritius.`}</p></div></div></section>
 <main className="wrap" style={{paddingTop:10,paddingBottom:80}}><div className="detail-grid"><div>
  <div className="hero-photo">{main?<img src={main.image_url} alt={hike.name}/>:<div className="hero-fallback" aria-hidden="true"/>}</div>
  {gallery.length>0&&<section style={{marginTop:18}}><div className="gallery-grid">{gallery.map((m,i)=><img key={m.id} src={m.image_url} alt={`${hike.name} gallery ${i+1}`} loading="lazy"/>)}</div></section>}
  <section className="logistics"><div><b>DISTANCE</b><span>{hike.distance_km!=null?`${hike.distance_km} km`:'TBC'}</span></div><div><b>ELEVATION</b><span>{hike.elevation_gain_m!=null?`${hike.elevation_gain_m} m`:'TBC'}</span></div><div><b>DURATION</b><span>{hike.duration}</span></div><div><b>FITNESS</b><span>{hike.fitness_required||'TBC'}</span></div></section>
  <section className="content-section"><h2>The experience</h2><p>{hike.description||`A guided route built around ${hike.main_attraction?.toLowerCase()||'the landscape of Mauritius'}.`}</p></section>
  <section className="content-section"><h2>Quick facts</h2><div className="facts">{facts.map(([label,val])=><div key={label}><b>{label}</b><span>{val}</span></div>)}</div></section>
  <section className="content-section"><h2>What you&apos;ll experience</h2><div className="chips">{[hike.main_attraction,...experience].filter(Boolean).map((x,i)=><span key={`${x}-${i}`}>✦ {x}</span>)}</div></section>
  {[['What to bring',bring],['What’s included',included],['What’s not included',excluded]].map(([title,items])=><section className="content-section" key={title as string}><h2>{title as string}</h2>{(items as string[]).length?<ul>{(items as string[]).map(x=><li key={x}>{x}</li>)}</ul>:<p className="muted">To be confirmed — final details are provided before booking.</p>}</section>)}
  <section className="content-section"><h2>Safety & logistics</h2>{[['Meeting point',hike.meeting_point],['Starting point',hike.starting_point],['Getting there',hike.transport_options],['Safety',hike.safety_info],['Weather policy',hike.weather_policy]].map(([label,val])=><div className="info" key={label as string}><b>{label as string}</b><p>{valueOr(val as string|null|undefined)}</p></div>)}</section>
 </div><aside className="booking-card"><div className="booking-label">{bookingLabel}</div><h2>{isScheduled?(hike.date||'Date to be confirmed'):'Choose your date'}</h2><p>{bookingType==='scheduled_group'?'A published departure you can join with other hikers.':bookingType==='private'?'A private outing arranged around your group and preferred date.':'Tell us when you want to go and we will arrange the route around conditions and availability.'}</p><div className="price"><small>GROUP RATE</small><strong>{hike.price_group_usd!=null?`$${hike.price_group_usd}`:hike.price}</strong>{hike.price_group_usd!=null&&<span>/person</span>}</div>{isScheduled&&<div className="spots">{available?`${spots} spots left`:'Fully booked'}</div>}<Link href={enquiry} className="book-btn">{routeUnavailable?'Ask about an alternative hike':available?(bookingType==='scheduled_group'?'Enquire / join this hike':bookingType==='private'?'Plan a private hike':'Plan this hike'):'Ask about a private hike'}</Link></aside></div></main>
 <style>{`.detail-grid{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(300px,.8fr);gap:32px;align-items:start}.hero-photo{width:100%;aspect-ratio:16/7;background:#e7e1d2;overflow:hidden}.hero-photo img{width:100%;height:100%;object-fit:cover;display:block}.hero-fallback{width:100%;height:100%;background:linear-gradient(145deg,#d9cfba,#1f4b4c 48%,#102b2b)}.gallery-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.gallery-grid img{width:100%;aspect-ratio:4/3;object-fit:cover;display:block;background:#e7e1d2}.logistics{margin-top:22px;display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--sand-line);background:var(--warm-white)}.logistics div{padding:16px;border-right:1px solid var(--sand-line)}.logistics div:last-child{border-right:0}.logistics b,.facts b{display:block;font-size:10px;letter-spacing:.09em;text-transform:uppercase;color:#777168}.logistics span{display:block;margin-top:6px;font-size:14px;font-weight:700}.content-section{margin-top:38px}.content-section h2{font-size:32px;margin-bottom:14px}.content-section p,.content-section li{font-size:15px;line-height:1.8;color:#3d3a36}.facts{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--sand-line);border-left:1px solid var(--sand-line)}.facts div{padding:16px;border-right:1px solid var(--sand-line);border-bottom:1px solid var(--sand-line)}.facts span{display:block;margin-top:6px;font-weight:650}.chips{display:flex;flex-wrap:wrap;gap:10px}.chips span{padding:12px 15px;border:1px solid var(--sand-line);background:rgba(250,248,243,.35)}.info{border-top:1px solid var(--sand-line);padding:13px 0}.info b{font-size:12px;text-transform:uppercase;letter-spacing:.06em}.info p{margin:5px 0 0;font-size:13px}.muted{color:#777168!important}.booking-card{position:sticky;top:96px;border:1px solid var(--sand-line);background:var(--warm-white);padding:24px;box-shadow:0 12px 32px rgba(0,0,0,.05)}.booking-label{display:inline-flex;padding:7px 10px;border:1px solid var(--sand-line);font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.booking-card h2{font-size:30px;margin:12px 0 8px}.booking-card>p{font-size:13px;line-height:1.6;color:#5a564f}.price{margin-top:20px;padding-top:18px;border-top:1px solid var(--sand-line)}.price small{display:block;font-size:11px;color:#5a564f}.price strong{font-size:28px}.price span{font-size:14px;margin-left:4px}.spots{margin-top:16px;font-size:12px;font-weight:700}.book-btn{display:block;text-align:center;margin-top:16px;background:var(--ember);color:var(--warm-white);padding:14px 20px;font-size:14px;font-weight:700}@media(max-width:760px){.detail-grid{grid-template-columns:1fr}.booking-card{position:static}.logistics{grid-template-columns:1fr 1fr}.logistics div:nth-child(2){border-right:0}.logistics div:nth-child(n+3){border-top:1px solid var(--sand-line)}.facts{grid-template-columns:1fr 1fr}.gallery-grid{grid-template-columns:1fr 1fr}}`}</style></div>
}
