import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import HomeClientPillars from '@/components/HomeClientPillars'
export const revalidate=0
export default async function HomePage(){
 const supabase=await createClient()
 const [{data:hikesData},{data:expedition},{data:teamData},{data:content},{data:settings},{data:testimonials},{data:instagramPosts}]=await Promise.all([
  supabase.from('hikes').select('id,name,difficulty,date,duration,location,price,spots_remaining').eq('status','published').order('created_at',{ascending:true}),
  supabase.from('expeditions').select('id,slug,name,destination,duration_days,price_from,next_departure,description').eq('status','published').order('created_at',{ascending:true}).limit(1).maybeSingle(),
  supabase.from('team_building_packages').select('id,name,type,description').eq('status','published'),
  supabase.from('homepage_content').select('*').eq('id',true).maybeSingle(),
  supabase.from('site_settings').select('instagram_handle,instagram_url').eq('id',true).maybeSingle(),
  supabase.from('testimonials').select('id,quote,name,activity').eq('status','published').order('sort_order',{ascending:true}).order('created_at',{ascending:true}).limit(6),
  supabase.from('instagram_posts').select('id,image_url,post_url,caption').eq('status','published').order('sort_order',{ascending:true}).order('created_at',{ascending:true}).limit(6),
 ])
 const c=content || {}
 const s=settings || {instagram_handle:'peak.axis',instagram_url:'https://www.instagram.com/peak.axis'}
 const reviews=testimonials||[]; const posts=instagramPosts||[]
 return <div id="view-home">
  <section className="hero"><svg className="contour-svg" viewBox="0 0 600 500" fill="none" aria-hidden="true"><path d="M50 400 C150 350, 200 480, 350 420 C500 360, 480 200, 580 150" stroke="#C9B790" strokeWidth="1" opacity=".4"/><path d="M20 320 C120 270, 180 390, 310 330 C440 270, 420 120, 550 80" stroke="#C9B790" strokeWidth="1" opacity=".5"/><path d="M80 450 C180 400, 220 500, 380 450 C520 400, 510 250, 590 200" stroke="#C1440E" strokeWidth="1.2" opacity=".35"/><path d="M100 250 C170 210, 240 290, 340 230 C440 170, 410 60, 520 20" stroke="#C9B790" strokeWidth="1" opacity=".4"/><path d="M150 180 C210 150, 280 210, 360 160 C440 110, 430 30, 490 10" stroke="#1F4B4C" strokeWidth="1.2" opacity=".3"/></svg><div className="wrap"><div className="hero-inner"><h1>{c.hero_title||'Adventure'} <span className="em">{c.hero_emphasis||'without'}</span><br/>{c.hero_title_suffix||'borders.'}</h1><p className="hero-sub">{c.hero_subtitle}</p><div className="hero-ctas"><Link href={c.hero_primary_url||'/hikes'} className="btn-primary">{c.hero_primary_cta||'View upcoming hikes'}</Link><Link href={c.hero_secondary_url||'/expeditions/piton-de-la-fournaise'} className="btn-ghost">{c.hero_secondary_cta||'Featured expedition'}</Link></div><div className="elev-marks">{[[c.elevation_1_value,c.elevation_1_label],[c.elevation_2_value,c.elevation_2_label],[c.elevation_3_value,c.elevation_3_label]].map(([v,l],i)=><div className="elev-mark" key={i}><div className="num">{v}</div><div className="lbl">{l}</div></div>)}</div></div></div></section>
  <section className="intro"><div className="wrap"><div className="intro-inner"><h2>{c.intro_title}</h2><p>{c.intro_body}</p></div></div></section>
  <HomeClientPillars hikes={hikesData||[]} expedition={expedition||null} teamBuilding={teamData||[]} copy={c}/>
  {expedition&&<section className="feat-band"><div className="wrap"><div className="band-inner"><div className="b-left"><span className="eyebrow">{c.featured_expedition_label}</span><h2>{expedition.name}</h2><p>{c.featured_expedition_description}</p><div className="b-stats"><div><span className="val">{c.featured_expedition_elevation}</span><span className="lbl">{c.featured_expedition_elevation_label}</span></div><div><span className="val">{expedition.duration_days} Days</span><span className="lbl">{c.featured_expedition_duration_label}</span></div><div><span className="val">{expedition.next_departure||'On request'}</span><span className="lbl">{c.featured_expedition_departure_label}</span></div></div></div><div className="b-right"><div className="price-tag">From {expedition.price_from}</div><Link href={`/expeditions/${expedition.slug}`} className="btn-ember">{c.featured_expedition_cta}</Link></div></div></div></section>}
  {reviews.length>0&&<section className="testimonials-strip"><div className="wrap"><div className="strip-head"><span className="kicker">{c.testimonials_kicker}</span><h2>{c.testimonials_title}</h2><p className="strip-sub">{c.testimonials_subtitle}</p></div><div className="reviews-grid">{reviews.map((r:any)=><div key={r.id} className="review-card"><div><div className="quote-mark">&ldquo;</div><p className="quote-body">{r.quote}</p></div><div className="review-meta"><strong className="author">{r.name}</strong><span className="hike-tag">{r.activity}</span></div></div>)}</div></div></section>}
  <section className="positioning"><div className="wrap"><div className="pos-inner"><h2>{c.positioning_title}<br/>{c.positioning_prefix} <span className="em">{c.positioning_emphasis}</span>.</h2><div className="pos-grid pos-grid-4">{[1,2,3,4].map(n=><div className="pos-card" key={n}><div className="num">0{n}</div><h3>{c[`why_${n}_title`]}</h3><p>{c[`why_${n}_body`]}</p></div>)}</div></div></div></section>
  <section className="instagram-section"><div className="wrap"><div className="insta-head"><span className="kicker">{c.instagram_kicker}</span><h2>{c.instagram_title_prefix} <a href={s.instagram_url} target="_blank" rel="noopener noreferrer">@{s.instagram_handle}</a></h2><p className="insta-sub">{c.instagram_subtitle}</p></div>{posts.length>0?<div className="insta-grid">{posts.map((p:any)=><a key={p.id} href={p.post_url} target="_blank" rel="noopener noreferrer" className="insta-post"><img src={p.image_url} alt={p.caption||`Peak Axis Instagram post`} loading="lazy"/><div className="insta-overlay"><span>{p.caption||`@${s.instagram_handle}`}</span><small>{c.instagram_overlay_cta}</small></div></a>)}</div>:<div className="insta-empty"><p>Add your latest Instagram posts from Admin → Site Content to display them here.</p><a href={s.instagram_url} target="_blank" rel="noopener noreferrer" className="btn-ghost">Follow @{s.instagram_handle}</a></div>}</div></section>
  <section className="cta-banner"><div className="wrap"><div className="banner-box"><h2>{c.cta_title}</h2><p>{c.cta_body}</p><Link href={c.cta_url||'/enquire'} className="btn-primary">{c.cta_button}</Link></div></div></section>
  <style>{`.testimonials-strip{padding:70px 0;background:#fffaf2;border-top:1px solid var(--sand-line);border-bottom:1px solid var(--sand-line)}.strip-head{margin-bottom:38px}.strip-head .kicker,.insta-head .kicker{color:var(--ember);font-size:11px;font-weight:800;letter-spacing:.1em;display:block;margin-bottom:10px}.strip-head h2,.insta-head h2{font-size:clamp(32px,5vw,54px)}.strip-sub,.insta-sub{margin-top:8px;color:#514c45;font-size:16px}.reviews-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}.review-card{background:var(--ash);border:1px solid var(--sand-line);padding:28px 24px;display:flex;flex-direction:column;justify-content:space-between;min-height:220px}.quote-mark{font-family:var(--font-display),sans-serif;font-size:54px;line-height:.5;color:var(--ember);margin-bottom:12px}.quote-body{font-size:15px;line-height:1.6;color:#3d3a36;font-style:italic;margin-bottom:20px}.review-meta{border-top:1px solid var(--sand-line);padding-top:14px;display:flex;flex-direction:column;gap:2px}.review-meta .author{font-size:14px;color:var(--ink)}.review-meta .hike-tag{font-size:12.5px;color:#6b675f}.pos-grid-4{display:grid;grid-template-columns:repeat(4,1fr);gap:24px;margin-top:40px}.instagram-section{padding:76px 0;border-top:1px solid var(--sand-line);background:#f5f1e8}.insta-head{margin-bottom:38px}.insta-head h2 a{color:inherit;text-decoration:underline;text-decoration-color:var(--ember);text-underline-offset:5px}.insta-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:14px}.insta-post{aspect-ratio:1/1;background:var(--teal);position:relative;overflow:hidden;display:block;border:1px solid var(--sand-line)}.insta-post img{width:100%;height:100%;object-fit:cover;display:block}.insta-overlay{position:absolute;inset:0;background:rgba(33,31,29,.7);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;color:var(--warm-white);opacity:0;transition:opacity .2s ease;padding:12px;text-align:center}.insta-post:hover .insta-overlay{opacity:1}.insta-overlay span{font-size:11px;font-weight:700}.insta-overlay small{font-size:10px;color:var(--sand);text-transform:uppercase;letter-spacing:.05em}.insta-empty{padding:42px;border:1px dashed var(--sand-line);text-align:center;background:var(--warm-white)}.insta-empty p{margin-bottom:18px;color:#514c45}@media(max-width:960px){.reviews-grid{grid-template-columns:1fr}.pos-grid-4{grid-template-columns:repeat(2,1fr)}.insta-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.pos-grid-4{grid-template-columns:1fr}.insta-grid{grid-template-columns:repeat(2,1fr)}}`}</style>
 </div>
}