'use client'

import { useState } from 'react'
import Link from 'next/link'

interface Hike { id: string; name: string; date: string; price: string; price_solo_usd: number; price_group_usd: number; hike_type: string; main_attraction: string }
interface Expedition { id: string; name: string; destination: string; price_from: string }
interface TeamPackage { id: string; name: string; type: string }
interface EnquiryFormClientProps { hikes: Hike[]; expeditions: Expedition[]; teamPackages: TeamPackage[]; initialInterest?: string; initialRef?: string }

export default function EnquiryFormClient({ hikes, expeditions, teamPackages, initialInterest = 'hike', initialRef = '' }: EnquiryFormClientProps) {
  const [interestType, setInterestType] = useState(initialInterest); const [referenceId, setReferenceId] = useState(initialRef)
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [phone, setPhone] = useState(''); const [preferredDate, setPreferredDate] = useState(''); const [groupSize, setGroupSize] = useState('2'); const [message, setMessage] = useState('')
  const [submitting, setSubmitting] = useState(false); const [submitted, setSubmitted] = useState(false); const [errorMsg, setErrorMsg] = useState('')
  const selectedHike = hikes.find((h) => h.name === referenceId); const parsedGroupSize = Number.parseInt(groupSize, 10)
  const estimatedTotal = selectedHike ? (parsedGroupSize === 1 ? selectedHike.price_solo_usd : parsedGroupSize * selectedHike.price_group_usd) : null
  const isDeuxMamelles = selectedHike?.name.toLowerCase().includes('deux mamelles')

  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); setSubmitting(true); setErrorMsg(''); try { const res = await fetch('/api/enquiries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: name.trim(), email: email.trim(), phone: phone.trim() || undefined, interest_type: interestType, reference_id: referenceId.trim() || undefined, preferred_date: preferredDate || undefined, group_size: groupSize, message: message.trim() || undefined }) }); const json = await res.json(); if (!res.ok) throw new Error(json.error || 'Failed to submit enquiry. Please try again.'); setSubmitted(true) } catch (err: unknown) { setErrorMsg(err instanceof Error ? err.message : 'An error occurred') } finally { setSubmitting(false) } }
  if (submitted) return <div className="wrap" id="formView"><div className="confirm show" role="alert" aria-live="polite"><h2>Enquiry sent.</h2><p>Thanks — we&apos;ve got your details. Our team will get back to you directly, usually within a day or two.</p></div></div>

  return <div className="wrap" id="formView"><form id="enquiryForm" onSubmit={handleSubmit}>
    {errorMsg && <div role="alert" style={{ padding: '12px 16px', background: '#C1440E', color: '#FAF8F3', marginBottom: '24px', fontWeight: 600 }}>{errorMsg}</div>}
    <div className="field"><span id="interest-label" style={{ display: 'block', fontSize: '13px', fontWeight: 600, color: '#3d3a36', marginBottom: '9px' }}>What are you interested in? *</span><div className="interest-grid" role="group" aria-labelledby="interest-label">{([['hike','Scheduled Group Hike','Join an upcoming weekend route'],['private_hike','Private Hike','Your trail, your group, your date'],['expedition','Volcano Expedition','Multi-day Piton de la Fournaise'],['team','Team Building','Corporate outdoor challenges'],['activity','Custom Activity','Group events or workshops']] as const).map(([value,title,sub]) => <button key={value} type="button" className={`interest-opt ${interestType === value ? 'active' : ''}`} onClick={() => { setInterestType(value); setReferenceId('') }}><div className="title">{title}</div><div className="sub">{sub}</div></button>)}</div></div>
    <div className="f-row"><div className="field"><label htmlFor="fullName">Full name *</label><input type="text" id="fullName" required value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Jean-Luc Marie" /></div><div className="field"><label htmlFor="email">Email address *</label><input type="email" id="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@domain.com" /></div></div>
    <div className="f-row"><div className="field"><label htmlFor="phone">Phone / WhatsApp</label><input type="tel" id="phone" value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="+230 5123 4567" /></div><div className="field"><label htmlFor="groupSize">Estimated group size</label><select id="groupSize" value={groupSize} onChange={(e) => setGroupSize(e.target.value)}>{[1,2,3,4,5,6,7,8,9,10].map(n => <option key={n} value={n}>{n === 1 ? 'Solo (1 person)' : `${n} people`}</option>)}<option value="11">11+ people (large group)</option></select></div></div>
    {interestType === 'hike' && <div className="cond show"><div className="field"><label htmlFor="hikeSelect">Select hike route</label><select id="hikeSelect" value={referenceId} onChange={(e) => setReferenceId(e.target.value)}><option value="">-- Choose a scheduled hike --</option>{hikes.map(h => <option key={h.id} value={h.name}>{h.name} ({h.date}) — {h.price}</option>)}</select></div>{selectedHike && estimatedTotal !== null && <div style={{ marginTop: '12px', padding: '14px 16px', border: '1px solid #d8d1c2' }}><strong>Estimated total: ${estimatedTotal.toLocaleString()} USD</strong><div style={{ marginTop: '4px', fontSize: '13px', color: '#5A564F' }}>{parsedGroupSize === 1 ? `Solo rate: $${selectedHike.price_solo_usd}` : `${parsedGroupSize} × $${selectedHike.price_group_usd} group rate`}</div></div>}{isDeuxMamelles && <div style={{ marginTop: '12px', padding: '14px 16px', background: '#eef4f0', borderLeft: '3px solid #1F4B4C' }}>💡 <strong>Want to add a refreshing waterfall swim?</strong> Check out the <strong>Deux Mamelles + Waterfalls</strong> experience ($50/person for groups)!</div>}</div>}
    {interestType === 'private_hike' && <div className="cond show"><div className="f-row"><div className="field"><label htmlFor="trailPref">Trail preference (optional)</label><input type="text" id="trailPref" value={referenceId} onChange={(e) => setReferenceId(e.target.value)} placeholder="e.g. Le Morne, Black River Gorges, or custom" /></div><div className="field"><label htmlFor="prefDatePrivate">Preferred date</label><input type="date" id="prefDatePrivate" value={preferredDate} onChange={(e) => setPreferredDate(e.target.value)} /></div></div></div>}
    {interestType === 'expedition' && <div className="cond show"><div className="field"><label htmlFor="expSelect">Expedition</label><select id="expSelect" value={referenceId} onChange={(e) => setReferenceId(e.target.value)}><option value="">-- Select expedition --</option>{expeditions.map(ex => <option key={ex.id} value={ex.name}>{ex.name} ({ex.destination}) — From {ex.price_from}</option>)}</select></div></div>}
    {interestType === 'team' && <div className="cond show"><div className="f-row"><div className="field"><label htmlFor="teamPkg">Package type</label><select id="teamPkg" value={referenceId} onChange={(e) => setReferenceId(e.target.value)}><option value="">-- Choose package --</option>{teamPackages.map(tp => <option key={tp.id} value={tp.name}>{tp.name} ({tp.type})</option>)}<option value="custom">Custom Team Package</option></select></div><div className="field"><label htmlFor="teamDate">Preferred date</label><input type="date" id="teamDate" value={preferredDate} onChange={(e) => setPreferredDate(e.target.value)} /></div></div></div>}
    {interestType === 'activity' && <div className="cond show"><div className="f-row"><div className="field"><label htmlFor="actType">Activity type</label><input type="text" id="actType" value={referenceId} onChange={(e) => setReferenceId(e.target.value)} /></div><div className="field"><label htmlFor="activityDate">Preferred date</label><input type="date" id="activityDate" value={preferredDate} onChange={(e) => setPreferredDate(e.target.value)} /></div></div></div>}
    <div className="field" style={{ marginTop: '20px' }}><label htmlFor="message">Anything else we should know?</label><textarea id="message" rows={4} value={message} onChange={(e) => setMessage(e.target.value)} /></div>
    <p style={{ fontSize: '13px', color: '#5A564F', marginBottom: '16px' }}>By submitting this form, you agree to our processing of your personal information as described in our <Link href="/privacy-policy" style={{ textDecoration: 'underline', color: 'var(--ink)', fontWeight: 600 }}>Privacy Policy</Link>.</p>
    <button type="submit" className="btn-primary" disabled={submitting}>{submitting ? 'Sending...' : 'Send enquiry'}</button>
  </form></div>
}
