'use client'

import { useState, useId } from 'react'
import Link from 'next/link'
import { getHikePriceEstimate } from '@/lib/hikePricing'

export interface HikeItem {
  id: string
  name: string
  date?: string
  price?: string
  price_solo_usd?: number
  price_group_usd?: number
  hike_type?: string
  main_attraction?: string
  difficulty?: string
  difficulty_numeric?: string
  duration?: string
  location?: string
  spots_remaining?: number
  spots_total?: number
  description?: string | null
}
export interface ExpeditionItem { id: string; name: string; destination: string; price_from: string; duration?: string; difficulty?: string; description?: string }
export interface TeamPackageItem { id: string; name: string; type: string; duration?: string; price_note?: string; description?: string }
interface EnquiryFormClientProps { hikes: HikeItem[]; expeditions: ExpeditionItem[]; teamPackages: TeamPackageItem[]; initialInterest?: string; initialRef?: string }
const INTEREST_OPTIONS = [
  ['hike', 'Scheduled Group Hike', 'Join an upcoming weekend route'],
  ['private_hike', 'Private Hike', 'Your trail, your group, your date'],
  ['expedition', 'Volcano Expedition', 'Multi-day Piton de la Fournaise'],
  ['team', 'Team Building', 'Outdoor challenges for teams'],
  ['activity', 'Custom Activity', 'Group events or workshops'],
] as const

export default function EnquiryFormClient({ hikes, expeditions, teamPackages, initialInterest = 'hike', initialRef = '' }: EnquiryFormClientProps) {
  const [interestType, setInterestType] = useState(initialInterest)
  const [referenceId, setReferenceId] = useState(initialRef)
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [phone, setPhone] = useState(''); const [preferredDate, setPreferredDate] = useState(''); const [groupSize, setGroupSize] = useState('2'); const [message, setMessage] = useState('')
  const [submitting, setSubmitting] = useState(false); const [submitted, setSubmitted] = useState(false); const [errorMsg, setErrorMsg] = useState('')
  const [submittedData, setSubmittedData] = useState<any>(null); const [touched, setTouched] = useState<Record<string, boolean>>({})
  const nameId=useId(), emailId=useId(), phoneId=useId(), groupSizeId=useId(), hikeSelectId=useId(), trailPrefId=useId(), prefDatePrivateId=useId(), expSelectId=useId(), teamPkgId=useId(), teamDateId=useId(), actTypeId=useId(), activityDateId=useId(), messageId=useId()
  const parsedGroupSize = Number.parseInt(groupSize, 10) || 1
  const selectedHike = interestType === 'hike' ? hikes.find(h => h.name === referenceId) : null
  const selectedExpedition = interestType === 'expedition' ? expeditions.find(ex => ex.name === referenceId) : null
  const selectedTeamPkg = interestType === 'team' ? teamPackages.find(tp => tp.name === referenceId) : null
  const isDeuxMamelles = selectedHike?.name.toLowerCase().includes('deux mamelles')
  const hikePriceEst = selectedHike && selectedHike.price_solo_usd !== undefined && selectedHike.price_group_usd !== undefined ? getHikePriceEstimate({price_solo_usd:selectedHike.price_solo_usd,price_group_usd:selectedHike.price_group_usd}, parsedGroupSize) : null
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); setTouched({name:true,email:true}); if(!name.trim()||!email.trim()){setErrorMsg('Please fill in all required fields.');return}; if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())){setErrorMsg('Please provide a valid email address.');return}; setSubmitting(true);setErrorMsg(''); const payload={name:name.trim(),email:email.trim(),phone:phone.trim()||undefined,interest_type:interestType,reference_id:referenceId.trim()||undefined,preferred_date:preferredDate||undefined,group_size:groupSize,message:message.trim()||undefined}; try{const res=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const json=await res.json();if(!res.ok)throw new Error(json.error||'Failed to submit enquiry. Please try again.');setSubmittedData({id:json.data?.id,...payload});setSubmitted(true)}catch(err:unknown){setErrorMsg(err instanceof Error?err.message:'An error occurred while submitting your enquiry.')}finally{setSubmitting(false)} }
  const interestTitle=(type:string)=>INTEREST_OPTIONS.find(([val])=>val===type)?.[1]||'Enquiry'
  if(submitted&&submittedData)return <div className="wrap"><div className="enquiry-success-card"><div className="success-badge">Enquiry received ✓</div><h2>Thank you, {submittedData.name}!</h2><p>We&apos;ve received your enquiry for <strong>{submittedData.reference_id||interestTitle(submittedData.interest_type)}</strong>. Our adventure guides will review your details and respond within <strong>24–48 hours</strong>.</p><div className="summary-recap-box"><h3>Summary of your request</h3><dl>{submittedData.reference_id&&<div><dt>Selected item</dt><dd>{submittedData.reference_id}</dd></div>}<div><dt>Group size</dt><dd>{submittedData.group_size==='11'?'11+ people':`${submittedData.group_size} ${submittedData.group_size==='1'?'person':'people'}`}</dd></div><div><dt>Email</dt><dd>{submittedData.email}</dd></div>{submittedData.preferred_date&&<div><dt>Preferred date</dt><dd>{submittedData.preferred_date}</dd></div>}</dl></div><div className="success-actions"><Link href="/hikes" className="btn-primary">Explore more hikes</Link><Link href="/" className="btn-secondary">Back to homepage</Link></div></div></div>
  return <div className="wrap" id="formView"><div className="enquiry-layout"><div className="enquiry-main-col">{referenceId&&<div className="referenced-item-card"><div className="ref-card-header"><span>Referenced Activity</span><button type="button" onClick={()=>setReferenceId('')}>Change activity ✕</button></div><h3>{referenceId}</h3>{interestType==='hike'&&selectedHike&&<div className="ref-card-meta">{selectedHike.date&&<span>📅 {selectedHike.date}</span>}{selectedHike.difficulty&&<span>⚡ {selectedHike.difficulty} {selectedHike.difficulty_numeric&&`(${selectedHike.difficulty_numeric})`}</span>}{selectedHike.duration&&<span>⏱ {selectedHike.duration}</span>}{selectedHike.location&&<span>📍 {selectedHike.location}</span>}</div>}</div>}
  <form onSubmit={handleSubmit} noValidate>{errorMsg&&<div role="alert" className="form-error-banner">⚠️ {errorMsg}</div>}<div className="field"><span className="field-label-bold">1. What are you interested in? <span className="req-star">*</span></span><div className="interest-grid">{INTEREST_OPTIONS.map(([value,title,sub])=><button key={value} type="button" className={`interest-opt ${interestType===value?'active':''}`} onClick={()=>{setInterestType(value);setReferenceId('')}}><div className="t">{title}</div><div className="s">{sub}</div></button>)}</div></div>
  {interestType==='hike'&&<div className="cond-section"><div className="field"><label htmlFor={hikeSelectId}>Select scheduled route</label><select id={hikeSelectId} value={referenceId} onChange={e=>setReferenceId(e.target.value)}><option value="">-- Choose a scheduled hike --</option>{hikes.map(h=><option key={h.id} value={h.name}>{h.name} {h.date?`(${h.date})`:''} {h.price?`— ${h.price}`:''}</option>)}</select></div>{isDeuxMamelles&&<div className="upsell-box">💡 <strong>Want to add a refreshing waterfall swim?</strong> Check out the <strong>Deux Mamelles + Waterfalls</strong> experience ($50/person for groups)!</div>}</div>}
  {interestType==='private_hike'&&<div className="cond-section"><div className="row2"><div className="field"><label htmlFor={trailPrefId}>Trail preference (optional)</label><input id={trailPrefId} value={referenceId} onChange={e=>setReferenceId(e.target.value)} placeholder="e.g. Le Morne, Black River Gorges, or custom route" /></div><div className="field"><label htmlFor={prefDatePrivateId}>Preferred date</label><input type="date" id={prefDatePrivateId} value={preferredDate} onChange={e=>setPreferredDate(e.target.value)} /></div></div></div>}
  {interestType==='expedition'&&<div className="cond-section"><div className="field"><label htmlFor={expSelectId}>Select expedition</label><select id={expSelectId} value={referenceId} onChange={e=>setReferenceId(e.target.value)}><option value="">-- Select expedition --</option>{expeditions.map(ex=><option key={ex.id} value={ex.name}>{ex.name} ({ex.destination}) — From {ex.price_from}</option>)}{!expeditions.some(ex=>ex.name===referenceId)&&referenceId&&<option value={referenceId}>{referenceId}</option>}<option value="Piton des Neiges Expedition">Piton des Neiges Expedition (La Réunion)</option></select></div></div>}
  {interestType==='team'&&<div className="cond-section"><div className="row2"><div className="field"><label htmlFor={teamPkgId}>Package type</label><select id={teamPkgId} value={referenceId} onChange={e=>setReferenceId(e.target.value)}><option value="">-- Choose package --</option>{teamPackages.map(tp=><option key={tp.id} value={tp.name}>{tp.name} ({tp.type})</option>)}<option value="Custom Team Package">Custom Team Package</option></select></div><div className="field"><label htmlFor={teamDateId}>Preferred date</label><input type="date" id={teamDateId} value={preferredDate} onChange={e=>setPreferredDate(e.target.value)} /></div></div></div>}
  {interestType==='activity'&&<div className="cond-section"><div className="row2"><div className="field"><label htmlFor={actTypeId}>Activity description / type</label><input id={actTypeId} value={referenceId} onChange={e=>setReferenceId(e.target.value)} placeholder="e.g. Workshop, photography trek, sunrise climb" /></div><div className="field"><label htmlFor={activityDateId}>Preferred date</label><input type="date" id={activityDateId} value={preferredDate} onChange={e=>setPreferredDate(e.target.value)} /></div></div></div>}
  <div className="field-group-heading">2. Your Details</div><div className="row2"><div className="field"><label htmlFor={nameId}>Full name <span className="req-star">*</span></label><input id={nameId} required value={name} onChange={e=>setName(e.target.value)} onBlur={()=>setTouched(p=>({...p,name:true}))} placeholder="e.g. Jean-Luc Marie" className={touched.name&&!name.trim()?'input-error':''}/></div><div className="field"><label htmlFor={emailId}>Email address <span className="req-star">*</span></label><input type="email" id={emailId} required value={email} onChange={e=>setEmail(e.target.value)} onBlur={()=>setTouched(p=>({...p,email:true}))} placeholder="you@domain.com"/></div></div>
  <div className="row2"><div className="field"><label htmlFor={phoneId}>Phone / WhatsApp</label><input type="tel" id={phoneId} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+230 5123 4567" /></div><div className="field"><label htmlFor={groupSizeId}>Estimated group size</label><select id={groupSizeId} value={groupSize} onChange={e=>setGroupSize(e.target.value)}>{[1,2,3,4,5,6,7,8,9,10].map(n=><option key={n} value={n}>{n===1?'Solo (1 person)':`${n} people`}</option>)}<option value="11">11+ people (large group)</option></select></div></div>
  {interestType==='hike'&&selectedHike&&hikePriceEst&&<div className="summary-pricing-box inline-price"><strong>{hikePriceEst.total!==null?`Estimated total: $${hikePriceEst.total.toLocaleString()} USD`:'Large group rate confirmed after enquiry'}</strong><p>{hikePriceEst.note||'Non-binding estimate.'}</p></div>}
  <div className="field"><label htmlFor={messageId}>Anything else we should know?</label><textarea id={messageId} rows={4} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Share fitness levels, dietary requirements, or any questions..." /></div><p className="privacy-notice">By submitting this enquiry, you agree to our processing of your personal information as described in our <Link href="/privacy-policy" className="legal-link">Privacy Policy</Link>.</p><button type="submit" className="btn-primary form-submit-btn" disabled={submitting}>{submitting?'Sending enquiry...':'Send enquiry'}</button></form></div>
  <aside className="enquiry-sidebar-col"><div className="sticky-summary-card"><h3 className="summary-title">Enquiry Summary</h3><div className="summary-section"><div className="summary-label">Category</div><div className="summary-value">{interestTitle(interestType)}</div></div><div className="summary-section"><div className="summary-label">Selected item</div><div className="summary-value highlight">{referenceId||<span className="placeholder-text">None selected</span>}</div></div>{preferredDate&&<div className="summary-section"><div className="summary-label">Preferred date</div><div className="summary-value">📅 {preferredDate}</div></div>}<div className="summary-section"><div className="summary-label">Party size</div><div className="summary-value">👥 {groupSize==='11'?'11+ people':`${parsedGroupSize} ${parsedGroupSize===1?'person':'people'}`}</div></div><div className="sidebar-trust-box"><div className="trust-item"><strong>Quick response</strong><span>Usually within 24–48 hours</span></div><div className="trust-item"><strong>No payment required</strong><span>Free, non-binding enquiry</span></div></div></div></aside></div></div>
}
