'use client'

import { useMemo, useState } from 'react'

type Status = 'new' | 'contacted' | 'quoted' | 'confirmed' | 'completed' | 'closed'
interface Enquiry { id:string; name:string; email:string; phone:string|null; interest_type:string; reference_id:string|null; preferred_date:string|null; group_size:string|null; message:string|null; status:Status; submitted_at:string }

const STATUS_OPTIONS: { value: Status; label: string }[] = [
  { value:'new', label:'New' }, { value:'contacted', label:'Contacted' }, { value:'quoted', label:'Quote Sent' },
  { value:'confirmed', label:'Confirmed' }, { value:'completed', label:'Completed' }, { value:'closed', label:'Closed' },
]
const styles = {
  card:{background:'var(--warm-white)',border:'1px solid var(--sand-line)',padding:'22px'},
  button:{padding:'9px 13px',border:'1px solid var(--ink)',background:'transparent',fontWeight:700,cursor:'pointer',fontSize:13} as const,
}

function replyFor(e: Enquiry) {
  const request = [e.reference_id, e.preferred_date ? `preferred date: ${e.preferred_date}` : '', e.group_size ? `group size: ${e.group_size}` : ''].filter(Boolean).join(', ')
  const greeting = `Hi ${e.name},`
  if (e.status === 'new') return `${greeting}\n\nThank you for getting in touch with Peak Axis regarding ${request || 'your enquiry'}.\n\nWe have received your request and are reviewing the details. We will get back to you shortly with the relevant information and next steps.\n\nKind regards,\nPeak Axis`
  if (e.status === 'contacted') return `${greeting}\n\nJust following up regarding your enquiry${request ? ` for ${request}` : ''}.\n\nPlease let us know if you have any questions or if you would like us to proceed with the next step.\n\nKind regards,\nPeak Axis`
  if (e.status === 'quoted') return `${greeting}\n\nThank you for your interest. We have prepared the quotation for your request${request ? ` (${request})` : ''}.\n\nPlease review the details and let us know if you would like to proceed, or if you would like us to adjust anything.\n\nKind regards,\nPeak Axis`
  if (e.status === 'confirmed') return `${greeting}\n\nThank you for confirming your plans with Peak Axis.\n\nWe are pleased to confirm the arrangements and will share the next steps and any remaining details with you.\n\nKind regards,\nPeak Axis`
  if (e.status === 'completed') return `${greeting}\n\nThank you for choosing Peak Axis. We hope you had a great experience with us.\n\nWe really appreciate your trust and would be delighted to welcome you again in the future.\n\nKind regards,\nPeak Axis`
  return `${greeting}\n\nWe wanted to follow up on your previous enquiry. If you are still interested, please let us know and we will be happy to help with the next steps.\n\nKind regards,\nPeak Axis`
}

export default function EnquiriesTable({ initialEnquiries }:{initialEnquiries:Enquiry[]}){
  const [enquiries,setEnquiries]=useState(initialEnquiries)
  const [query,setQuery]=useState(''); const [status,setStatus]=useState<'all'|Status>('all'); const [interest,setInterest]=useState('all')
  const [selected,setSelected]=useState<Enquiry|null>(null); const [loadingId,setLoadingId]=useState<string|null>(null); const [reply,setReply]=useState('')
  const filtered=useMemo(()=>enquiries.filter(e=>{const hay=`${e.name} ${e.email} ${e.phone||''} ${e.reference_id||''} ${e.message||''}`.toLowerCase();return (!query||hay.includes(query.toLowerCase()))&&(status==='all'||e.status===status)&&(interest==='all'||e.interest_type===interest)}),[enquiries,query,status,interest])
  const counts=useMemo(()=>({total:enquiries.length,new:enquiries.filter(e=>e.status==='new').length,contacted:enquiries.filter(e=>e.status==='contacted').length,quoted:enquiries.filter(e=>e.status==='quoted').length,confirmed:enquiries.filter(e=>e.status==='confirmed').length,completed:enquiries.filter(e=>e.status==='completed').length}),[enquiries])
  const interests=Array.from(new Set(enquiries.map(e=>e.interest_type).filter(Boolean)))
  const updateStatus=async(id:string,next:Status)=>{setLoadingId(id);try{const r=await fetch(`/api/admin/enquiries/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:next})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Failed to update status');setEnquiries(p=>p.map(e=>e.id===id?{...e,status:next}:e));setSelected(s=>s?.id===id?{...s,status:next}:s)}catch(e){alert(e instanceof Error?e.message:'Failed to update status')}finally{setLoadingId(null)}}
  const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text)}catch{alert('Copy failed. Please select and copy the text manually.')}}
  const open=(e:Enquiry)=>{setSelected(e);setReply(replyFor(e))}
  const badge=(value:string,kind='default')=><span style={{display:'inline-block',padding:'4px 8px',fontSize:11,fontWeight:800,textTransform:'uppercase',letterSpacing:'.03em',background:kind==='teal'?'var(--teal)':kind==='ember'?'var(--ember)':kind==='sand'?'var(--sand)':'#5a564f',color:kind==='sand'?'var(--ink)':'#fff'}}>{value.replaceAll('_',' ')}</span>

  return <div>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:20,marginBottom:22}}><div><div style={{fontSize:10,fontWeight:800,letterSpacing:'.12em',color:'var(--ember)'}}>ENQUIRY WORKFLOW</div><h1 style={{fontFamily:'Big Shoulders Display',fontWeight:900,fontSize:44,textTransform:'uppercase',margin:'5px 0 7px'}}>Enquiries</h1><p style={{color:'#5a564f',margin:0}}>Read, reply, copy into Gmail, and move each request to its next stage.</p></div><button style={styles.button} onClick={()=>{setQuery('');setStatus('all');setInterest('all')}}>Reset filters</button></div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:12,marginBottom:16}}>{[['Total',counts.total,'#5a564f'],['New',counts.new,'var(--ember)'],['Contacted',counts.contacted,'var(--teal)'],['Quoted',counts.quoted,'#5a564f'],['Confirmed',counts.confirmed,'var(--teal)'],['Completed',counts.completed,'#5a564f']].map(([label,count,bg])=><div key={String(label)} style={{...styles.card,padding:'16px 18px'}}><div style={{fontSize:11,fontWeight:800,textTransform:'uppercase',color:'#625d55'}}>{label}</div><div style={{fontSize:28,fontWeight:800,marginTop:4,color:bg as string}}>{count}</div></div>)}</div>
    <div style={{...styles.card,marginBottom:16,display:'grid',gridTemplateColumns:'minmax(220px,1fr) 180px 170px',gap:10}}><input aria-label="Search enquiries" placeholder="Search name, email, phone, activity…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">All statuses</option>{STATUS_OPTIONS.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select><select value={interest} onChange={e=>setInterest(e.target.value)}><option value="all">All interests</option>{interests.map(i=><option key={i} value={i}>{i.replaceAll('_',' ')}</option>)}</select></div>
    <div style={{...styles.card,padding:0,overflow:'hidden'}}><div style={{padding:'12px 18px',borderBottom:'1px solid var(--sand-line)',fontSize:12,color:'#625d55'}}>{filtered.length} matching {filtered.length===1?'enquiry':'enquiries'}</div><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',textAlign:'left',fontSize:14,minWidth:900}}><thead><tr>{['Submitted','Customer','Interest','Request','Stage','Action'].map(h=><th key={h} style={{padding:'12px 16px',fontSize:11,textTransform:'uppercase',color:'#5a564f',borderBottom:'2px solid var(--sand-line)'}}>{h}</th>)}</tr></thead><tbody>{filtered.map(e=><tr key={e.id} style={{borderBottom:'1px solid var(--sand-line)',verticalAlign:'top'}}><td style={{padding:'15px 16px',whiteSpace:'nowrap',color:'#625d55',fontSize:12}}>{new Date(e.submitted_at).toLocaleDateString()}<br/>{new Date(e.submitted_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</td><td style={{padding:'15px 16px'}}><strong>{e.name}</strong><div style={{fontSize:12,color:'#625d55'}}>{e.email}</div>{e.phone&&<div style={{fontSize:12,color:'#625d55'}}>{e.phone}</div>}</td><td style={{padding:'15px 16px'}}>{badge(e.interest_type,e.interest_type==='hike'||e.interest_type==='team'?'teal':e.interest_type==='expedition'?'ember':'sand')}{e.reference_id&&<div style={{fontSize:12,marginTop:6,fontWeight:600}}>{e.reference_id}</div>}</td><td style={{padding:'15px 16px',maxWidth:330}}>{e.preferred_date&&<div style={{fontSize:12}}>Date: {e.preferred_date}</div>}{e.group_size&&<div style={{fontSize:12}}>Group size: {e.group_size}</div>}{e.message&&<div style={{fontSize:12.5,marginTop:5,color:'#3d3a36',lineHeight:1.45}}>{e.message.length>120?`${e.message.slice(0,120)}…`:e.message}</div>}</td><td style={{padding:'15px 16px'}}>{badge(e.status,e.status==='new'?'ember':e.status==='contacted'||e.status==='confirmed'?'teal':e.status==='quoted'?'sand':'default')}</td><td style={{padding:'15px 16px'}}><button style={styles.button} onClick={()=>open(e)}>Open workspace</button></td></tr>)}{filtered.length===0&&<tr><td colSpan={6} style={{padding:42,textAlign:'center',color:'#625d55'}}>No enquiries match these filters.</td></tr>}</tbody></table></div></div>
    {selected&&<div role="dialog" aria-modal="true" onClick={e=>{if(e.target===e.currentTarget)setSelected(null)}} style={{position:'fixed',inset:0,zIndex:100,background:'rgba(0,0,0,.5)',display:'flex',justifyContent:'flex-end'}}><aside style={{width:'min(680px,100%)',height:'100%',background:'var(--warm-white)',padding:28,overflowY:'auto',boxShadow:'-8px 0 30px rgba(0,0,0,.12)'}}>
      <div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'flex-start'}}><div><div style={{fontSize:10,fontWeight:800,letterSpacing:'.12em',color:'var(--ember)'}}>ENQUIRY WORKSPACE</div><h2 style={{fontFamily:'Big Shoulders Display',fontSize:34,textTransform:'uppercase',margin:'5px 0'}}>{selected.name}</h2><div style={{color:'#625d55',fontSize:13}}>{new Date(selected.submitted_at).toLocaleString()}</div></div><button aria-label="Close" style={{...styles.button,fontSize:18}} onClick={()=>setSelected(null)}>×</button></div>
      <div style={{marginTop:22,padding:16,border:'1px solid var(--sand-line)',background:'#fff'}}><div style={{fontSize:10,fontWeight:800,letterSpacing:'.1em',color:'#625d55'}}>STAGE</div><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:10}}>{STATUS_OPTIONS.map(({value,label})=><button key={value} disabled={loadingId===selected.id} onClick={()=>updateStatus(selected.id,value)} style={{...styles.button,padding:'7px 10px',background:selected.status===value?'var(--ink)':'transparent',color:selected.status===value?'#fff':'var(--ink)'}}>{label}</button>)}</div></div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:16}}><div style={{...styles.card,padding:16}}><div style={{fontSize:10,fontWeight:800,color:'#625d55'}}>CONTACT</div><div style={{marginTop:8,fontWeight:700}}>{selected.name}</div><div style={{fontSize:13,marginTop:3}}>{selected.email}</div>{selected.phone&&<div style={{fontSize:13,marginTop:3}}>{selected.phone}</div>}<button style={{...styles.button,marginTop:12}} onClick={()=>copy(selected.email)}>Copy email</button></div><div style={{...styles.card,padding:16}}><div style={{fontSize:10,fontWeight:800,color:'#625d55'}}>REQUEST</div><div style={{marginTop:8}}>{badge(selected.interest_type)}</div>{selected.reference_id&&<div style={{fontSize:13,marginTop:8}}><b>Activity:</b> {selected.reference_id}</div>}{selected.preferred_date&&<div style={{fontSize:13,marginTop:4}}><b>Date:</b> {selected.preferred_date}</div>}{selected.group_size&&<div style={{fontSize:13,marginTop:4}}><b>Group:</b> {selected.group_size}</div>}</div></div>
      <div style={{...styles.card,marginTop:16}}><div style={{fontSize:10,fontWeight:800,color:'#625d55'}}>ORIGINAL MESSAGE</div><div style={{whiteSpace:'pre-wrap',lineHeight:1.6,marginTop:10}}>{selected.message||'No message supplied.'}</div></div>
      <div style={{marginTop:16,padding:18,border:'2px solid var(--ink)',background:'#fff'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><div><div style={{fontSize:10,fontWeight:800,letterSpacing:'.1em',color:'var(--ember)'}}>NEXT ACTION</div><h3 style={{fontFamily:'Big Shoulders Display',fontSize:28,textTransform:'uppercase',margin:'3px 0'}}>Copy reply to Gmail</h3></div><button style={{...styles.button,background:'var(--ink)',color:'#fff'}} onClick={()=>copy(reply)}>Copy reply</button></div><div style={{marginTop:14}}><label style={{fontSize:11,fontWeight:800}}>TO</label><div style={{display:'flex',gap:8,marginTop:5}}><input value={selected.email} readOnly style={{flex:1,padding:'10px 12px',border:'1px solid var(--sand-line)',font: 'inherit'}}/><button style={styles.button} onClick={()=>copy(selected.email)}>Copy</button></div></div><div style={{marginTop:12}}><label style={{fontSize:11,fontWeight:800}}>SUBJECT</label><div style={{display:'flex',gap:8,marginTop:5}}><input value={`Re: ${selected.reference_id || selected.interest_type.replaceAll('_',' ')} enquiry`} onChange={()=>{}} readOnly style={{flex:1,padding:'10px 12px',border:'1px solid var(--sand-line)',font: 'inherit'}}/><button style={styles.button} onClick={()=>copy(`Re: ${selected.reference_id || selected.interest_type.replaceAll('_',' ')} enquiry`)}>Copy</button></div></div><div style={{marginTop:12}}><label style={{fontSize:11,fontWeight:800}}>REPLY — EDIT BEFORE SENDING</label><textarea value={reply} onChange={e=>setReply(e.target.value)} rows={13} style={{width:'100%',marginTop:5,padding:12,border:'1px solid var(--sand-line)',font:'inherit',lineHeight:1.55,resize:'vertical'}}/></div></div>
      <div style={{marginTop:16,display:'flex',justifyContent:'flex-end'}}><button style={{...styles.button,background:'var(--teal)',color:'#fff',borderColor:'var(--teal)'}} onClick={()=>updateStatus(selected.id,'contacted')}>Mark Contacted</button></div>
    </aside></div>}
    <style>{`@media(max-width:900px){.card[style*="repeat(6"]{grid-template-columns:repeat(3,1fr)!important}}@media(max-width:680px){.card[style*="repeat(6"]{grid-template-columns:repeat(2,1fr)!important}.card[style*="minmax(220px"]{grid-template-columns:1fr!important}.card[style*="1fr 1fr"]{grid-template-columns:1fr!important}}select,input,textarea{font:inherit}`}</style>
  </div>
}
