'use client'

import { useEffect, useMemo, useState } from 'react'

type Waterfall={id:string;name:string;location:string;duration:string;status:'draft'|'published';short_line:string|null}
const blank:Partial<Waterfall>={name:'',location:'',duration:'3 hrs',status:'draft',short_line:''}

export default function AdminWaterfallsPage(){
 const [items,setItems]=useState<Waterfall[]>([]);const [editing,setEditing]=useState<Partial<Waterfall>|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [query,setQuery]=useState('');const [status,setStatus]=useState<'all'|'draft'|'published'>('all')
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/admin/waterfalls',{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error||'Failed to load waterfalls');setItems(j.data||[])}catch(e){setError(e instanceof Error?e.message:'Failed to load waterfalls')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>items.filter(i=>(!query||`${i.name} ${i.location} ${i.short_line||''}`.toLowerCase().includes(query.toLowerCase()))&&(status==='all'||i.status===status)),[items,query,status])
 const counts={total:items.length,published:items.filter(i=>i.status==='published').length,draft:items.filter(i=>i.status==='draft').length}
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!editing)return;setSaving(true);try{const edit=Boolean(editing.id);const r=await fetch(edit?`/api/admin/waterfalls/${editing.id}`:'/api/admin/waterfalls',{method:edit?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:editing.name,location:editing.location,duration:editing.duration,short_line:editing.short_line,status:editing.status||'draft'})});const j=await r.json();if(!r.ok||!j.success)throw Error(j.error||'Failed to save waterfall');setEditing(null);await load()}catch(e){alert(e instanceof Error?e.message:'Failed to save waterfall')}finally{setSaving(false)}}
 const remove=async(id:string)=>{if(!confirm('Delete this waterfall route? This cannot be undone.'))return;setSaving(true);try{const r=await fetch(`/api/admin/waterfalls/${id}`,{method:'DELETE'});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Failed to delete waterfall');await load()}catch(e){alert(e instanceof Error?e.message:'Failed to delete waterfall')}finally{setSaving(false)}}
 const toggle=async(item:Waterfall)=>{const next=item.status==='published'?'draft':'published';setSaving(true);try{const r=await fetch(`/api/admin/waterfalls/${item.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...item,status:next})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Failed to update status');setItems(p=>p.map(x=>x.id===item.id?{...x,status:next}:x))}catch(e){alert(e instanceof Error?e.message:'Failed to update status')}finally{setSaving(false)}}
 return <div><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:20,marginBottom:22}}><div><div style={{fontSize:10,fontWeight:800,letterSpacing:'.12em',color:'var(--ember)'}}>ROUTE MANAGEMENT</div><h1 style={{fontFamily:'Big Shoulders Display',fontSize:44,fontWeight:900,textTransform:'uppercase',margin:'5px 0 7px'}}>Waterfalls</h1><p style={{color:'#5a564f',margin:0}}>Manage waterfall routes shown on the public site. Pricing is intentionally not stored here.</p></div><button onClick={()=>setEditing({...blank})} style={{background:'var(--ember)',color:'#fff',border:0,padding:'12px 20px',fontWeight:700,cursor:'pointer'}}>+ Add Waterfall</button></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:12,marginBottom:16}}>{[['Total',counts.total],['Published',counts.published],['Drafts',counts.draft]].map(([l,n])=><div key={String(l)} style={{background:'var(--warm-white)',border:'1px solid var(--sand-line)',padding:'16px 18px'}}><div style={{fontSize:11,fontWeight:800,textTransform:'uppercase',color:'#625d55'}}>{l}</div><div style={{fontSize:28,fontWeight:800,marginTop:4}}>{n}</div></div>)}</div>
 <div style={{background:'var(--warm-white)',border:'1px solid var(--sand-line)',padding:18,display:'grid',gridTemplateColumns:'1fr 180px',gap:10,marginBottom:16}}><input placeholder="Search route, location or description…" value={query} onChange={e=>setQuery(e.target.value)} style={{padding:'10px 12px',border:'1px solid var(--sand-line)'}}/><select value={status} onChange={e=>setStatus(e.target.value as typeof status)} style={{padding:'10px 12px',border:'1px solid var(--sand-line)'}}><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Draft</option></select></div>
 <div style={{background:'var(--warm-white)',border:'1px solid var(--sand-line)',padding:0,overflow:'hidden'}}>{error&&<div role="alert" style={{padding:16,color:'var(--ember)'}}>{error}</div>}{loading?<div style={{padding:32,color:'#625d55'}}>Loading waterfalls…</div>:<div style={{overflowX:'auto'}}><table style={{width:'100%',minWidth:760,borderCollapse:'collapse',textAlign:'left'}}><thead><tr>{['Route','Location','Duration','Status','Actions'].map(h=><th key={h} style={{padding:'12px 16px',fontSize:11,textTransform:'uppercase',color:'#5a564f',borderBottom:'2px solid var(--sand-line)'}}>{h}</th>)}</tr></thead><tbody>{filtered.map(item=><tr key={item.id} style={{borderBottom:'1px solid var(--sand-line)'}}><td style={{padding:'15px 16px'}}><strong>{item.name}</strong>{item.short_line&&<div style={{fontSize:12,color:'#625d55',marginTop:3}}>{item.short_line}</div>}</td><td style={{padding:'15px 16px'}}>{item.location}</td><td style={{padding:'15px 16px'}}>{item.duration}</td><td style={{padding:'15px 16px'}}><button onClick={()=>toggle(item)} disabled={saving} style={{padding:'5px 9px',border:0,cursor:'pointer',background:item.status==='published'?'var(--teal)':'#5a564f',color:'#fff',fontSize:11,fontWeight:800,textTransform:'uppercase'}}>{item.status}</button></td><td style={{padding:'15px 16px'}}><button onClick={()=>setEditing({...item})} style={{padding:'8px 12px',border:'1px solid var(--ink)',background:'transparent',fontWeight:700,cursor:'pointer'}}>Edit</button><button onClick={()=>remove(item.id)} disabled={saving} style={{padding:'8px 12px',border:'1px solid var(--ember)',background:'transparent',color:'var(--ember)',fontWeight:700,cursor:'pointer',marginLeft:8}}>Delete</button></td></tr>)}{filtered.length===0&&<tr><td colSpan={5} style={{padding:40,textAlign:'center',color:'#625d55'}}>No waterfall routes match the current filters.</td></tr>}</tbody></table></div>}</div>
 {editing&&<div role="dialog" aria-modal="true" onClick={e=>{if(e.target===e.currentTarget)setEditing(null)}} style={{position:'fixed',inset:0,zIndex:100,background:'rgba(0,0,0,.5)',display:'flex',alignItems:'center',justifyContent:'center',padding:20}}><form onSubmit={save} style={{background:'var(--warm-white)',width:'100%',maxWidth:640,maxHeight:'90vh',overflowY:'auto',padding:28,display:'grid',gap:16}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start'}}><div><div style={{fontSize:10,fontWeight:800,letterSpacing:'.12em',color:'var(--ember)'}}>WATERFALL ROUTE</div><h2 style={{fontFamily:'Big Shoulders Display',fontSize:32,textTransform:'uppercase',margin:'5px 0'}}> {editing.id?'Edit Waterfall':'Add Waterfall'}</h2></div><button type="button" onClick={()=>setEditing(null)} style={{border:'1px solid var(--ink)',background:'transparent',fontSize:18,padding:'4px 10px',cursor:'pointer'}}>×</button></div>
 {([['Route name *','name'],['Location *','location'],['Duration *','duration']] as const).map(([label,key])=><label key={key} style={{fontSize:12,fontWeight:800,textTransform:'uppercase'}}>{label}<input required value={(editing[key] as string)||''} onChange={e=>setEditing({...editing,[key]:e.target.value})} style={{display:'block',width:'100%',marginTop:6,padding:11,border:'1px solid var(--sand-line)'}}/></label>)}
 <label style={{fontSize:12,fontWeight:800,textTransform:'uppercase'}}>Short description<textarea rows={5} value={editing.short_line||''} onChange={e=>setEditing({...editing,short_line:e.target.value})} style={{display:'block',width:'100%',marginTop:6,padding:11,border:'1px solid var(--sand-line)'}}/></label><div style={{padding:'11px 13px',background:'#f5f1e8',fontSize:13,color:'#625d55',lineHeight:1.5}}>No pricing field: waterfall bookings can be discussed on request.</div><label style={{fontSize:12,fontWeight:800,textTransform:'uppercase'}}>Publishing<select value={editing.status||'draft'} onChange={e=>setEditing({...editing,status:e.target.value as Waterfall['status']})} style={{display:'block',width:'100%',marginTop:6,padding:11,border:'1px solid var(--sand-line)'}}><option value="draft">Draft</option><option value="published">Published</option></select></label><div style={{display:'flex',justifyContent:'flex-end',gap:10}}><button type="button" onClick={()=>setEditing(null)} style={{padding:'10px 16px',background:'transparent',border:'1px solid var(--ink)',cursor:'pointer'}}>Cancel</button><button type="submit" disabled={saving} style={{padding:'10px 20px',background:'var(--ember)',color:'#fff',border:0,fontWeight:700,cursor:'pointer'}}>{saving?'Saving…':'Save Waterfall'}</button></div></form></div>}
 <style>{`@media(max-width:680px){.page-head{flex-direction:column!important;align-items:stretch!important}.card{grid-template-columns:1fr!important}table{font-size:13px}}select,input,textarea{font:inherit}`}</style></div>
}
