'use client'
import { useEffect,useState } from 'react'
type Post={id:string;image_url:string;post_url:string;caption:string;status:'draft'|'published';sort_order:number}
type Testimonial={id:string;quote:string;name:string;activity:string;status:'draft'|'published';sort_order:number}
type Content=Record<string,string>
const sections=[
 ['Hero',['hero_title','hero_emphasis','hero_title_suffix','hero_subtitle','hero_primary_cta','hero_primary_url','hero_secondary_cta','hero_secondary_url','elevation_1_value','elevation_1_label','elevation_2_value','elevation_2_label','elevation_3_value','elevation_3_label']],
 ['Intro',['intro_title','intro_body']],
 ['Experience pillars',['hikes_title','hikes_body','hikes_primary_cta','hikes_primary_url','hikes_secondary_cta','hikes_secondary_url','expeditions_title','expeditions_body','expeditions_cta','expeditions_url','team_title','team_body','team_cta','team_url','activities_title','activities_body','activities_cta','activities_url']],
 ['Featured expedition',['featured_expedition_label','featured_expedition_description','featured_expedition_elevation','featured_expedition_elevation_label','featured_expedition_duration_label','featured_expedition_departure_label','featured_expedition_cta']],
 ['Why Peak Axis',['positioning_title','positioning_prefix','positioning_emphasis','why_1_title','why_1_body','why_2_title','why_2_body','why_3_title','why_3_body','why_4_title','why_4_body']],
 ['Testimonials section',['testimonials_kicker','testimonials_title','testimonials_subtitle']],
 ['Instagram section',['instagram_kicker','instagram_title_prefix','instagram_subtitle','instagram_overlay_cta']],
 ['Final CTA',['cta_title','cta_body','cta_button','cta_url']],
] as const
const label=(key:string)=>key.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const blankPost={image_url:'',post_url:'',caption:'',status:'published' as const,sort_order:0}
export default function SiteContentAdminPage(){
 const [homepage,setHomepage]=useState<Content>({}); const [settings,setSettings]=useState({instagram_handle:'peak.axis',instagram_url:'https://www.instagram.com/peak.axis'}); const [testimonials,setTestimonials]=useState<Testimonial[]>([]); const [posts,setPosts]=useState<Post[]>([]); const [editingTestimonial,setEditingTestimonial]=useState<Partial<Testimonial>|null>(null); const [editingPost,setEditingPost]=useState<Partial<Post>|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/admin/site-content');const j=await r.json();if(!r.ok)throw Error(j.error||'Failed to load');setHomepage(j.homepage||{});setSettings(j.settings||settings);setTestimonials(j.testimonials||[]);setPosts(j.instagram_posts||[])}catch(e){setError(e instanceof Error?e.message:'Failed to load')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const saveHomepage=async()=>{setSaving(true);const r=await fetch('/api/admin/site-content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({homepage,instagram_handle:settings.instagram_handle,instagram_url:settings.instagram_url})});const j=await r.json();setSaving(false);if(!r.ok)return alert(j.error||'Failed to save');setHomepage(j.homepage||homepage);alert('Site content saved')}
 const saveTestimonial=async(e:React.FormEvent)=>{e.preventDefault();if(!editingTestimonial)return;setSaving(true);const id=editingTestimonial.id;const r=await fetch(id?`/api/admin/testimonials/${id}`:'/api/admin/testimonials',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editingTestimonial)});const j=await r.json();setSaving(false);if(!r.ok)return alert(j.error||'Failed to save');setEditingTestimonial(null);load()}
 const savePost=async(e:React.FormEvent)=>{e.preventDefault();if(!editingPost)return;setSaving(true);const id=editingPost.id;const r=await fetch(id?`/api/admin/instagram-posts/${id}`:'/api/admin/instagram-posts',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editingPost)});const j=await r.json();setSaving(false);if(!r.ok)return alert(j.error||'Failed to save');setEditingPost(null);load()}
 const remove=async(url:string)=>{if(!confirm('Delete this item?'))return;const r=await fetch(url,{method:'DELETE'});if(!r.ok){const j=await r.json();alert(j.error||'Failed to delete')}else load()}
 if(loading)return <p>Loading…</p>
 return <div><h1 style={{fontFamily:'Big Shoulders Display',fontSize:36,fontWeight:900,textTransform:'uppercase'}}>Site Content</h1><p style={{color:'#5a564f',marginBottom:24}}>Everything below is editable without changing the code.</p>{error&&<p role="alert">{error}</p>}
  {sections.map(([title,fields])=><section key={title} style={{background:'var(--warm-white)',border:'1px solid var(--sand-line)',padding:24,marginBottom:18}}><h2>{title}</h2><div style={{display:'grid',gap:14,gridTemplateColumns:'repeat(2,minmax(0,1fr))'}}>{fields.map(k=><label key={k} style={{display:'block',gridColumn:k.includes('body')||k.includes('subtitle')||k.includes('description')?'1 / -1':'auto'}}>{label(k)}{k.includes('body')||k.includes('subtitle')||k.includes('description')?<textarea rows={4} value={homepage[k]||''} onChange={e=>setHomepage({...homepage,[k]:e.target.value})} style={{display:'block',width:'100%',padding:10,marginTop:6}}/>:<input value={homepage[k]||''} onChange={e=>setHomepage({...homepage,[k]:e.target.value})} style={{display:'block',width:'100%',padding:10,marginTop:6}}/>}</label>)}</div></section>)}
  <section style={{background:'var(--warm-white)',border:'1px solid var(--sand-line)',padding:24,marginBottom:18}}><h2>Instagram profile</h2><div style={{display:'grid',gap:14,maxWidth:700}}><label>Handle<input value={settings.instagram_handle} onChange={e=>setSettings({...settings,instagram_handle:e.target.value})} style={{display:'block',width:'100%',padding:10,marginTop:6}}/></label><label>Profile URL<input type="url" value={settings.instagram_url} onChange={e=>setSettings({...settings,instagram_url:e.target.value})} style={{display:'block',width:'100%',padding:10,marginTop:6}}/></label></div><button onClick={saveHomepage} disabled={saving} style={{marginTop:14}}>Save site content</button></section>
  <section style={{background:'var(--warm-white)',border:'1px solid var(--sand-line)',padding:24,marginBottom:18}}><div style={{display:'flex',justifyContent:'space-between'}}><div><h2>Testimonials</h2><p>Only publish genuine customer feedback.</p></div><button onClick={()=>setEditingTestimonial({quote:'',name:'',activity:'',status:'published',sort_order:0})}>+ Add testimonial</button></div><table style={{width:'100%',marginTop:16}}><tbody>{testimonials.map(t=><tr key={t.id}><td>{t.name}</td><td>{t.activity}</td><td>{t.status}</td><td><button onClick={()=>setEditingTestimonial({...t})}>Edit</button>{' '}<button onClick={()=>remove(`/api/admin/testimonials/${t.id}`)}>Delete</button></td></tr>)}</tbody></table></section>
  <section style={{background:'var(--warm-white)',border:'1px solid var(--sand-line)',padding:24}}><div style={{display:'flex',justifyContent:'space-between'}}><div><h2>Instagram posts</h2><p>Add real post images and links. Nothing is fabricated on the public site.</p></div><button onClick={()=>setEditingPost({...blankPost})}>+ Add post</button></div><table style={{width:'100%',marginTop:16}}><tbody>{posts.map(p=><tr key={p.id}><td>{p.caption||p.image_url}</td><td>{p.status}</td><td><button onClick={()=>setEditingPost({...p})}>Edit</button>{' '}<button onClick={()=>remove(`/api/admin/instagram-posts/${p.id}`)}>Delete</button></td></tr>)}</tbody></table></section>
  {editingTestimonial&&<div className="modal"><form onSubmit={saveTestimonial} className="modal-card"><h2>{editingTestimonial.id?'Edit testimonial':'New testimonial'}</h2><label>Quote<textarea required rows={5} value={editingTestimonial.quote||''} onChange={e=>setEditingTestimonial({...editingTestimonial,quote:e.target.value})}/></label><label>Name<input required value={editingTestimonial.name||''} onChange={e=>setEditingTestimonial({...editingTestimonial,name:e.target.value})}/></label><label>Activity<input required value={editingTestimonial.activity||''} onChange={e=>setEditingTestimonial({...editingTestimonial,activity:e.target.value})}/></label><label>Status<select value={editingTestimonial.status||'published'} onChange={e=>setEditingTestimonial({...editingTestimonial,status:e.target.value as 'draft'|'published'})}><option value="draft">Draft</option><option value="published">Published</option></select></label><label>Order<input type="number" value={editingTestimonial.sort_order??0} onChange={e=>setEditingTestimonial({...editingTestimonial,sort_order:Number(e.target.value)})}/></label><div><button type="button" onClick={()=>setEditingTestimonial(null)}>Cancel</button>{' '}<button disabled={saving}>Save</button></div></form></div>}
  {editingPost&&<div className="modal"><form onSubmit={savePost} className="modal-card"><h2>{editingPost.id?'Edit Instagram post':'New Instagram post'}</h2><label>Image URL<input required type="url" value={editingPost.image_url||''} onChange={e=>setEditingPost({...editingPost,image_url:e.target.value})}/></label><label>Instagram post URL<input required type="url" value={editingPost.post_url||''} onChange={e=>setEditingPost({...editingPost,post_url:e.target.value})}/></label><label>Caption<input value={editingPost.caption||''} onChange={e=>setEditingPost({...editingPost,caption:e.target.value})}/></label><label>Status<select value={editingPost.status||'published'} onChange={e=>setEditingPost({...editingPost,status:e.target.value as 'draft'|'published'})}><option value="draft">Draft</option><option value="published">Published</option></select></label><label>Order<input type="number" value={editingPost.sort_order??0} onChange={e=>setEditingPost({...editingPost,sort_order:Number(e.target.value)})}/></label><div><button type="button" onClick={()=>setEditingPost(null)}>Cancel</button>{' '}<button disabled={saving}>Save</button></div></form></div>}
  <style>{`.modal{position:fixed;inset:0;background:rgba(0,0,0,.5);display:flex;align-items:center;justify-content:center;padding:20px;z-index:100}.modal-card{background:var(--warm-white);padding:30px;width:100%;max-width:650px;display:grid;gap:14px}.modal-card input,.modal-card textarea,.modal-card select{display:block;width:100%;padding:10px;margin-top:6px}`}</style>
 </div>
}
