'use client'

import { useEffect, useState } from 'react'

type Post = { id: string; title: string; category: string; summary: string; content: string; status: 'draft' | 'published' }
const blank: Partial<Post> = { title: '', category: 'TRAIL GUIDES', summary: '', content: '', status: 'published' }

export default function AdminJournalPage() {
  const [posts, setPosts] = useState<Post[]>([])
  const [editing, setEditing] = useState<Partial<Post> | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const r = await fetch('/api/admin/journal'); const j = await r.json(); if (!r.ok) throw new Error(j.error || 'Failed to load'); setPosts(j.data || []) } catch (e) { setError(e instanceof Error ? e.message : 'Failed to load') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const save = async (e: React.FormEvent) => { e.preventDefault(); if (!editing) return; const edit = Boolean(editing.id); const r = await fetch(edit ? `/api/admin/journal/${editing.id}` : '/api/admin/journal', { method: edit ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...editing, content: editing.content || '' }) }); const j = await r.json(); if (!r.ok || !j.success) return alert(j.error || 'Failed to save'); setEditing(null); load() }
  const remove = async (id: string) => { if (!confirm('Delete this journal article?')) return; const r = await fetch(`/api/admin/journal/${id}`, { method: 'DELETE' }); if (!r.ok) { const j = await r.json(); alert(j.error || 'Failed to delete') } else load() }
  const input = (label: string, key: keyof Post, area = false) => <label style={{ display: 'block', fontSize: 12, fontWeight: 700, textTransform: 'uppercase' }}>{label}{area ? <textarea rows={7} value={(editing?.[key] as string) || ''} onChange={e => setEditing({ ...editing, [key]: e.target.value })} style={{ display: 'block', width: '100%', marginTop: 6, padding: 10 }} /> : <input value={(editing?.[key] as string) || ''} onChange={e => setEditing({ ...editing, [key]: e.target.value })} style={{ display: 'block', width: '100%', marginTop: 6, padding: 10 }} />}</label>
  return <div><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 24 }}><div><h1 style={{ fontFamily: 'Big Shoulders Display', fontSize: 36, fontWeight: 900, textTransform: 'uppercase' }}>Journal</h1><p style={{ color: '#5a564f' }}>Write, edit, publish and update field notes.</p></div><button onClick={() => setEditing({ ...blank })} style={{ background: 'var(--ember)', color: '#fff', border: 0, padding: '12px 20px' }}>+ New Article</button></div><div style={{ background: 'var(--warm-white)', border: '1px solid var(--sand-line)', padding: 24 }}>{error ? <p role="alert">{error}</p> : loading ? <p>Loading…</p> : <table style={{ width: '100%', borderCollapse: 'collapse' }}><thead><tr>{['Title','Category','Status','Actions'].map(x => <th key={x} style={{ textAlign: 'left', padding: 12, borderBottom: '2px solid var(--sand-line)', fontSize: 12 }}>{x}</th>)}</tr></thead><tbody>{posts.map(p => <tr key={p.id}><td style={{ padding: 12 }}>{p.title}</td><td style={{ padding: 12 }}>{p.category}</td><td style={{ padding: 12 }}>{p.status}</td><td style={{ padding: 12 }}><button onClick={() => setEditing({ ...p })} style={{ marginRight: 8 }}>Edit</button><button onClick={() => remove(p.id)}>Delete</button></td></tr>)}</tbody></table>}</div>{editing && <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20, zIndex: 100 }}><form onSubmit={save} style={{ background: 'var(--warm-white)', padding: 30, width: '100%', maxWidth: 700, display: 'grid', gap: 16, maxHeight: '90vh', overflow: 'auto' }}><h2 style={{ fontFamily: 'Big Shoulders Display', fontSize: 28, textTransform: 'uppercase' }}>{editing.id ? 'Edit Article' : 'New Article'}</h2>{input('Title *', 'title')}{input('Category *', 'category')}{input('Summary *', 'summary', true)}{input('Article content *', 'content', true)}<label style={{ display: 'block', fontSize: 12, fontWeight: 700, textTransform: 'uppercase' }}>Status<select value={editing.status || 'published'} onChange={e => setEditing({ ...editing, status: e.target.value as Post['status'] })} style={{ display: 'block', width: '100%', marginTop: 6, padding: 10 }}><option value="draft">Draft</option><option value="published">Published</option></select></label><div style={{ display: 'flex', justifyContent: 'flex-end', gap: 10 }}><button type="button" onClick={() => setEditing(null)}>Cancel</button><button type="submit">Save Article</button></div></form></div>}</div>
}
